### ISSUE TITLE
.NET 7 or 8?

### ISSUE THREAD

**Issue by Jay-o-Way** [U-C-S/Hurl#104]
Changelog for latest say

> Move to .NET 8 Desktop Runtime, instead of .NET 7 ([Download it here](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.3-windows-x64-installer))

but installing it shows
![image](https://github.com/U-C-S/Hurl/assets/65828559/3363d450-fd25-46a2-a1a4-164178096c51)

**Comment by U-C-S** [comment]
`.NET 8` my bad 😅

Fixed it

**Comment by Jay-o-Way** [comment]
Oh, by the way: it would be good practice to remove the `en-us/` part from links
