### ISSUE TITLE
Zombie Processes Being Created

### ISSUE THREAD

**Issue by war59312** [U-C-S/Hurl#134]
Hi,

Looks like there is a bug in hurl somewhere that is causing zombie processes to stick around, at least using with Edge on 11 23H2.

Can see for yourself using https://github.com/zodiacon/ObjectExplorer then System and Zombie Process and Threads.

Thankfully not a ton of them but it is happening every time hurl is used it seems. 

Thankfully closing or reloading hurl does make them go away, so at least correctly cleaned up on closing.

FindZombieHandles from https://github.com/BobVul/FindZombieHandles also confirms same behavior.

Best,

Will

**Comment by U-C-S** [comment]
Thanks for this.... 

I will have a look, Have to see what processes/threads it makes a zombie off

**Comment by U-C-S** [comment]
Forgot reply here earlier.

I see zombies get cleaned up in a minute or so. This shouldn't be a much of issue I believe.
