### ISSUE TITLE
HURL v0.9.0-alpha-3 Not Respecting Windows Shutdown/Restart - Uknown Error

### ISSUE THREAD

**Issue by war59312** [U-C-S/Hurl#152]
Hi,

Went to reboot my Win11 23H2 box after installing the Aug Windows Security updates and got an error trying to reboot and then realized it was HURL:

![signal-2024-08-16-102624](https://github.com/user-attachments/assets/741d857c-49e9-44f6-a599-d39a146f1b46)

Win11 23 H2
HURL v0.9.0-alpha-3

Was only showing one of the errors. I right clicked hurl's notification (system tray) icon and it displayed a 2nd error.

Tried a few times as can be seen in the screenshot. After about 20 tries or so, hurl crashed. Then of course my machine could reboot fine.

So, looks like need to test if windows is being rebooted or shutdown and close out correctly beforehand.

Looks like need to be watching for the SystemEvents.SessionEnding Event @  https://learn.microsoft.com/en-us/dotnet/api/microsoft.win32.systemevents.sessionending?view=net-8.0&redirectedfrom=MSDN

Best,

Will

**Comment by U-C-S** [comment]
This is the weirdest error/behavior I've seen for Hurl yet 😅. I do restart/shutdown frequently with Hurl always in background, never seen it so far.

I suspect this related to how I am handling Exit calls for threads, currently I just forcefully kill threads and main process for Hurl. I want to fix this before stable release.

I could be wrong about this completely.

**Comment by U-C-S** [comment]
Implemented better exit behaviour: https://github.com/U-C-S/Hurl/commit/abbbbdeba0a9f9f8155354f8e245add80bd54c2b

**Comment by U-C-S** [comment]
I am closing this cause there is no way of verifying if the supposed fix works.
but if this appears again, Just comment here and I am ready to open this again.
