### ISSUE TITLE
New Hurl install on Windows 11, not auto-opening browser based on rules.

### ISSUE THREAD

**Issue by HankLloydRight** [U-C-S/Hurl#158]
I'm migrating my Hurl config from Win10 to Win11. Works great on Win10, but on Win11, when I click on any link, it opens up the Hurl app with the browser icons (Hurl is default browser), but it does not automatically launch the link in the target browser based on Regex rules (as it does on Win10).  
 I copied the JSON file from Win10 to Win11 and only had to update the path for Vivaldi.. the other browsers Chrome and Edge were already set up.  
Here's my JSON file (with parts redacted).
Thanks.

```
{
  "$schema": "https://raw.githubusercontent.com/U-C-S/Hurl/main/Utils/UserSettings.schema.json",
  "LastUpdated": "8/29/2024 11:08:34 AM",
  "Browsers": [
    {
      "Name": "Google Chrome",
      "ExePath": "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"
    },
    {
      "Name": "Microsoft Edge",
      "ExePath": "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"
    },
    {
      "Name": "Vivaldi",
      "ExePath": "C:\\Users\\HankLloydRight\\AppData\\Local\\Vivaldi\\Application\\vivaldi.exe"
    }
  ],
  "AppSettings": {
    "LaunchUnderMouse": true,
    "NoWhiteBorder": false,
    "BackgroundType": "acrylic",
    "RuleMatching": true,
    "WindowSize": [
      420,
      210
    ]
  },
  "Rulesets": [
    {
      "Rules": [
        "r$r$^(?!.*\\bdomain\\.com\\b).*"
      ],
      "RulesetName": "Non domain.com links go to Chrome",
      "BrowserName": "Google Chrome"
    },
    {
      "Rules": [
        "r$r$\\bdomain\\.com\\b"
      ],
      "RulesetName": "domain.com to Vivaldi",
      "BrowserName": "Vivaldi"
    }
  ]
}```

**Comment by U-C-S** [comment]
Thanks for opening the issue.

I will have a look at this weekend.

**Comment by U-C-S** [comment]
> r$r$^(?!.*\\bdomain\\.com\\b).*
> r$r$\\bdomain\\.com\\b

Probably because `r$r$` instead of `r$` ?

**Comment by HankLloydRight** [comment]
Duh.. I'm an idiot. I didn't catch that.  I'm not sure how or why the r$ got repeated, but it's working now!

Thanks for your help.  Case closed.

**Comment by HankLloydRight** [comment]
Duh.. I'm an idiot. I didn't catch that.  I'm not sure how or why the r$ got repeated, but it's working now!

Thanks for your help.  Case closed.
