### ISSUE TITLE
Forward Compatible Windows App Runtime?

### ISSUE THREAD

**Issue by mix3d** [U-C-S/Hurl#165]
Windows App Runtime url link (when not installed) mentions the 1.5 version, but Windows has released 1.6 as the default, and Hurl still complains when you use that version. Clicking yes on the error window takes you to the 1.6 download page. 

Is it possible to have Hurl work in a forward compatible manner with newer versions, or is there something about this package that _requires_ 1.5 in a non-upgradable way?

![image](https://github.com/user-attachments/assets/7cd0a881-11a1-4f92-8505-1210b6219b86)
https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads
![image](https://github.com/user-attachments/assets/486ae52b-a56f-45be-bec9-086460d7392f)

**Comment by U-C-S** [comment]
Didn't realize this would be a issue.

This discussion https://github.com/microsoft/WindowsAppSDK/discussions/3657 has some info about it that Hurl might have to implement it. so yes, currently windows app runtime by default is not foward compatible, but version locked, which I have to opt-out.

**Comment by U-C-S** [comment]
To make this work, figured out I can ship a certain dependency from the Redistributable (`MSIX > win10-x64 > *-DDLM.msix`, which is around 100kb in size) of a specific version that Hurl Settings uses, which probably the installer can install.

**Comment by U-C-S** [comment]
https://github.com/U-C-S/Hurl/pull/171#issuecomment-2458643973
