### ISSUE TITLE
Can not debug solution

### ISSUE THREAD

**Issue by Jay-o-Way** [U-C-S/Hurl#167]
I just tried to debug/run Hurl project on my computer and I can't get it to work. I have a lot of errors and warnings.

Two possiblities:

- Can be related to the two latest commits
- I updated to Win 11, 24H2, build **26100.1742** yesterday

I have already deleted my online and local repository, and then re-cloned it.

A selection of messages I see:

- MSB3073	Warning (active)	**The command ""C:\Users\jmpaa\.nuget\packages\microsoft.windows.cswinrt\2.1.5\cswinrt.exe" @"R:\Hurl\Source\Hurl.BrowserSelector\obj\Debug\net8.0-windows10.0.26100.0\Generated Files\CsWinRT\cswinrt.rsp"" exited with code 1**.	C:\Users\jmpaa\.nuget\packages\microsoft.windows.cswinrt\2.1.5\build\Microsoft.Windows.CsWinRT.targets	292	5	Build	
- NETSDK1206	Warning (active)	**Found version-specific or distribution-specific runtime identifier(s): win10-arm64, win10-x64, win10-x86. Affected libraries: Microsoft.WindowsAppSDK. In .NET 8.0 and higher, assets for version-specific and distribution-specific runtime identifiers will not be found by default. See https://aka.ms/dotnet/rid-usage for details.**	C:\Program Files\dotnet\sdk\8.0.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets	284	5	Build	
- WMC1006	Warning (active)	**Cannot resolve Assembly or Windows Metadata file 'R:\Hurl\Source\Hurl.Library\bin\Debug\net8.0-windows\Hurl.Library.dll'**	R:\Hurl\Source\Hurl.Settings\Hurl.Settings.csproj	1	1	Build

**Comment by Jay-o-Way** [comment]
Right after creating this issue, I remember to open Visual Studio Installer and install **Windows 11 SDK 10.0.26100.0**
After this, I don't see the same warnings - this means this SDK version is crucial to have. Worth noting in documentation/readme.
But now it still doesn't work. I have 45 warnings and most of them mention **CsWinRT**:

- CsWinRT1029	Warning (active)	**Class 'ViewRulesDialog' implements WinRT interface(s) IUIElementOverrides, IAnimationObject, IVisualElement, IVisualElement2, IFrameworkElementOverrides, IControlOverrides, IPageOverrides, IComponentConnector generated using an older version of CsWinRT.  Update to a projection generated using CsWinRT 2.1.0 or later for trimming and AOT compatibility.** (https://github.com/microsoft/CsWinRT/tree/master/src/Authoring/WinRT.SourceGenerator/AnalyzerReleases.Shipped.md)	R:\Hurl\Source\Hurl.Settings\Views\Dialogs\ViewRulesDialog.xaml.cs	8	29	Build

**Comment by U-C-S** [comment]
> iewRulesDialog' implements WinRT interface(s) IUIElementOverrides, IAnimationObject, IVisualElement, IVisualElement2, IFrameworkElementOverrides, IControlOverrides, IPageOverrides, IComponentConnector generated using an older version of CsWinRT. Update to a projection generated using CsWinRT 2.1.0 or later for trimming and AOT compatibi

I had these warnings only once a while ago they cleared after I "clean solution" and build again. I am not sure either.

**Comment by U-C-S** [comment]
> A selection of messages I see:

>    MSB3073 Warning (active)

But I never had these issues before though.
Though I recently upgraded the sdk version used by `Hurl.Settings` project to 26100 but it's still a stash

**Comment by Jay-o-Way** [comment]
Well, good news. It's working again. No idea what happened.
