### ISSUE TITLE
C:\Program Files (x86)\Hurl\LICENSE MoveFile failed; code 183

### ISSUE THREAD

**Issue by elvisisvan** [U-C-S/Hurl#170]
current version: 0.8.3.20
![hurl-v0.8.3.2](https://github.com/user-attachments/assets/f4644cd4-4db8-48cf-997a-a4f144c9cdf7)
update version: 0.9.0
os: windows 10

---

cannot update to v0.9.0 due to error 183: 
```
C:\Program Files (x86)\Hurl\LICENSE

An error occurred while trying to rename a file in the destination directory:
MoveFile failed; code 183.
Cannot create a file when that file already exists.
```
![errorcode183](https://github.com/user-attachments/assets/fe585e40-f79e-46fb-9db6-4731be03e4f4)

**Comment by elvisisvan** [comment]
> Uninstall the previous version before installing the newer version (known issue with 0.9.0)

should i uninstall from windows app settings or control panel? (to ensure complete uninstallation)

**Comment by U-C-S** [comment]
Either way it's the same.... anything should be fine

**Comment by U-C-S** [comment]
Closing it since it's already a known issue and mentioned in the release notes for v0.9
