### ISSUE TITLE
Trying to run/debug fresh clone gives error for .NET

### ISSUE THREAD

**Issue by Jay-o-Way** [U-C-S/Hurl#180]
Installed Windows 11 (24H2) and apps cleanly a couple of weeks ago now. Got a fresh fork and clone, now trying to run/debug the solution. Got an error:

> ❌ Unable to resolve the .NET SDK version as specified in the global.json located at S:\Hurl\global.json.

and warning

> ⚠️ Unable to locate the .NET SDK version '8.0.300' as specified by global.json, please check that the specified version is installed.

Simply deleting file _global.json_ solves the problem. Should this be adopted in the repo?

**Comment by U-C-S** [comment]
Had this issue. iirc, correctly, Visual Studio's newer minor update uninstalls the .NET 8 SDK and installs the .NET 9 SDK. fixed it by manually installing .NET 8 SDK.

try `dotnet --list-sdks` once and check if .NET 8 is available in your system

**Comment by Jay-o-Way** [comment]
Okay. VS Installer shows Runtime v8 and v9, but running the command shows only v`9.0.100`. As said, simply deleting the json file makes the problem go away, so does the project **need** 8 or 9? And does a specific build-version matter? Because there are a lot of versions on https://dotnet.microsoft.com/download/dotnet/8.0
![image](https://github.com/user-attachments/assets/3007b580-0255-45bf-9fc9-af89b368c95b)

**Comment by U-C-S** [comment]
Project needs .NET 8

CI needs it now that to build it correctly. since dotnet build always uses latest available version in the system. [this](https://learn.microsoft.com/en-us/dotnet/core/tools/global-json) is only way to point it out to only use `.NET 8` not 9 or 10.


> there are a lot of versions
```json
    "version": "8.0.300",
    "rollForward": "latestMinor"
```
the `rollForward` takes care of that. any `8.*.*` is valid

**Comment by Jay-o-Way** [comment]
> Project needs .NET 8

But apparently it also works fine if 8 isn't available.

Anyways, I installed 8 so problem solved.
