### ISSUE TITLE
Expand width to fit all available browser

### ISSUE THREAD

**Issue by nitin2953** [U-C-S/Hurl#25]
It is showing like this on Widnows 10
App version: v0.4.0-alpha

![image](https://user-images.githubusercontent.com/34852979/157457854-7c848573-a697-4079-be84-445c25acc3ae.png)

**Comment by U-C-S** [comment]
Thanks for feedback. I was actually thinking about using horizontal scroll bars. Do you think they'll be a good idea ?

Or why not both, with a setting to choose either...

**Comment by U-C-S** [comment]
Thanks for visualization. Currently I committed the code for having a minwidth. And seems the scrollbar thing has bit of UI problem. WPF uses ugly fat scrollbars which take out the look of App. Either I need to design a custom scrollbar or wait or Fix myself the Horizontal Scroll bar issue in WPFUI (https://github.com/lepoco/wpfui/issues/58)

Also, What do you thing of having multiple rows ??

**Comment by nitin2953** [comment]
> Also, What do you think of having multiple rows ??

A Grid
but I think it would distract user focus (if he is in hurry), lead him to ?precisely? place pointer on icon


![chrome_dRGMx8HDjm](https://user-images.githubusercontent.com/34852979/157483732-8ab62dea-5442-4493-8324-c7e630785ac1.png)

**Comment by U-C-S** [comment]
![image](https://user-images.githubusercontent.com/50218121/164291291-0070a184-7e7b-46db-9cc8-2be7304d8d47.png)

I think it's looking good for now. Scrollbar goes hidden automatically.
