### ISSUE TITLE
Drop context menu for `•••` OR `👤`

### ISSUE THREAD

**Issue by nitin2953** [U-C-S/Hurl#36]
Make context-menu look like tray's menu
OR drop context menu instead use a <kbd>•••</kbd> OR <kbd>👤</kbd> icon at bottom-right corner,
Newcomer won't know that they can right click on it

**Comment by U-C-S** [comment]
![image](https://user-images.githubusercontent.com/50218121/160848464-50a0d498-4922-45c1-8017-b7bf859c0862.png)

Something like this. Yes it's a good idea. Design not final though and that button will be made visible only when mouse is hovered. 

I might need to worry about empty space created by it. A interesting design challenge nevertheless.

**Comment by U-C-S** [comment]
<img src="https://user-images.githubusercontent.com/50218121/179299067-aacd86ea-8b81-4be2-a45c-873c88561273.gif" width="500" />

Done. It's working but implemented in weird way. Waiting for DropDown Button support in WPF-UI.
