### ISSUE TITLE
Slow Dragging Bug [Windows 10]

### ISSUE THREAD

**Issue by grentninja** [U-C-S/Hurl#39]
Hello! Thank you for your hardwork here, and the Hurl software really helped me a lot! I have yet to find any software like this (except Browser Select). I only found your software from the Browser Select GitHub page.

I found a bug. When you drag the Hurl UI in Windows 10, it lags when you hold and drag. I found a temporary fix with this for now. If you close the transparency in Windows 10 Personalize > Colors Tab, you will eventually have no lags when dragging. The only problem is if you want the transparency tab in Windows 10 along with no Hurl Lagging Drag since I use the transparency effect on my windows taskbar.

Thank you, and I really appreciate your effort in making Hurl :)

**Comment by U-C-S** [comment]
Thanks for the appreciation 💖.

Temporarily, I can provide a option to disable the transparency option as a workaround. I haven't got a proper chance to test Hurl in windows 10, since I personally use Win 11. 

if possible, can you provide your system specs ? CPU and GPU would be fine.

**Comment by grentninja** [comment]
Thanks for this! I think I would prefer that as well since transparency in Hurl is not my priority as well. 

Yes sure, this is my specs:
Ryzen 7 2700X
Radeon RX Vega 64
16 GB Ram
620W PSU
B450 Motherboard
Samsung 860 EVO 1TB SSD

**Comment by U-C-S** [comment]
Already, Working on this option. Though first, I might need to refactor the code a bit.

There are already few problems with Acrylic and the library that provides it, I had to throw bunch of workarounds to make it work. So, It's already a magic for me that Acrylic is working for WPF in the first place. (I'm waiting for WinAppSDK v1.1 release, if u know what it is)

(decent specs btw)

**Comment by grentninja** [comment]
I have a a very little experience with coding, but I am quite interested about this. I'll probably search for these terminologies haha. But, it's nice to know you are already working on it :)

(thanks! been reliable to me for 4 years now and counting)

**Comment by nitin2953** [comment]
I have _Transparency Effect_ disabled all time.
Noticed this bug now

https://user-images.githubusercontent.com/34852979/164199404-0bc3e7fe-f298-4187-9021-6a4ea59b45b5.mp4
