### ISSUE TITLE
Feature Request: Parameter in UserSettings and custom icons

### ISSUE THREAD

**Issue by hanjo** [U-C-S/Hurl#43]
Hi,

first of all: great App!

Sometimes I'm getting links to Office documents (Excel, PowerPoint, Word), that I would like to open directly in the respective app.

This is possible by using C:\Program Files\Microsoft Office\root\Office16\protocolhandler.exe as the browser with the argument ms-excel:ofe|u|https://... (for Excel)

to make this work, it would be required to have a parameter for the URL though that I can put into the LaunchArgs. Something like %URL% or $1, so the LaunchArgs would become ms-excel:ofe|u|%URL%

For the same use case, it would also be helpful to select a custom icon, since the icon of protocolhandler.exe is a generic Office icon, which obviously becomes confusing if you configure it three times for Excel, PowerPoint and Word.

Let me know what you think!

Thanks

- [x] Custom Icons 
- [ ] Parameter in UserSettings.json

**Comment by U-C-S** [comment]
Yeh.... This might be possible and quite a easy one. I'll try to include it in v0.7

**Comment by U-C-S** [comment]
Added both of them in v0.6.2 

Report any issues on those if you got time.

**Comment by grentninja** [comment]
Ello! Just another suggestion related to the custom icons. 
Is it possible to make it suppose GIF image extensions? I would be great for more customization :>

**Comment by U-C-S** [comment]
GIFs.... I never thought about them. I don't know whether the underlying framework of Hurl (named WPF) supports it or not. Will look into it again.

**Comment by grentninja** [comment]
It's alright if it's not possible, just a wacky suggestion of mine lol

**Comment by hanjo** [comment]
I extracted 256x256 PNGs with alpha channel from the office executables and was able to use them using the CustomIconPath. Working nicely, thanks!
![CustomIconPath](https://user-images.githubusercontent.com/442966/172592866-80b2b1a4-fc71-4447-8638-60382f2ee42c.png)
