### ISSUE TITLE
Feature Request: Hotkeys

### ISSUE THREAD

**Issue by hanjo** [U-C-S/Hurl#44]
Hi,

I got another idea which - I think - would be a great addition to the app:

It would be great if it was possible to assign hotkeys for each browser. For example, after clicking the link, I press "F" for Firefox, "C" for Chrome and "E" for Edge, or even simpler 1,2,3

Another usability improvement would be to have the window open where the mouse cursor is, as opposed to the center of the screen, so the path to the desired browser is shorter.

Let me know what you think.

Thanks!

**Comment by andreysaksonov** [comment]
window at cursor position is a must for multi-monitor  setups

**Comment by U-C-S** [comment]
@andreysaksonov window at cursor position is already available, but disabled by default.

Check out the docs: https://github.com/U-C-S/Hurl/wiki/Application-Settings

**Comment by hanjo** [comment]
thanks for adding the "window at cursor position" functionality, I can confirm that it works in v0.7.1.

I'd like to propose one more change to this feature: Right now the windows top left corner opens where the cursor is. From my point of view it would be more intuitive if the window opens such that the center of the window is located at the cursor, that also means shorter distance to most icons.

**Comment by U-C-S** [comment]
> opens such that the center of the window is located at the cursor

Might need to do bit of mathematics there. but possible. I will see if that's makes UX better.

**Comment by U-C-S** [comment]
Basic Hotkeys implemented as of https://github.com/U-C-S/Hurl/commit/106966666750fc7f46eb4698ce3827a137949987

1-9 keys to select a browser
E, R, T, C for Edit URL, Quick Rule Adding, Timed Default, Copy URL respectively

**Comment by Shodoman2** [comment]
> 1-9 keys to select a browser
1-9 keys don't do anything. 
do i have to change something in UserSettings? 

The others work though there are some issues. Edit minimizes the window and when i bring back Hurl, weather through the tray icon or another link, i can see the edit window, i believe on top of main window. 
But clicking anywhere (x incon, ok, cancel, the link, any space in the window, outside the window) minimizes the window again so i have to Reload the app. Hovering over the buttons or link highlights them.

**Comment by U-C-S** [comment]
You are right, thanks for notifying.... in the released alpha build, it seems they are bugged. will fix them in the upcoming alpha release

**Comment by U-C-S** [comment]
The 1-9 keys... feat will be released in upcoming alpha alongside fixing of all the issues you mentioned

**Comment by U-C-S** [comment]
Closing this since Hotkeys are now available in v0.8 release. Custom Hotkeys will included in a future release, for further discussion, consider opening a new issue....
