### ISSUE TITLE
Firefox Incognito Link Opening

### ISSUE THREAD

**Issue by grentninja** [U-C-S/Hurl#46]
Hello everyone,

I just want to ask if there is a way that I can open links using Firefox incognito? Recently, I used this format here (as it also has been mentioned in the Firefox's official website).

`    {
      "Name": "Firefox",
      "ExePath": "C:\\Program Files\\Mozilla Firefox\\firefox.exe",
      "LaunchArgs": null,
      "Hidden": false,
      "AlternateLaunches": [
	  {
		  "ItemName": "Incognito",
		  "LaunchArgs": "-private-window"
	  }
	  ]
    },`

Although this works when I open incognito mode without a link, it does not work as intended when you have a link and you choose `Incognito` in the Firefox Alternate Launcher. It goes to open the Non-Private Window and the link within that Non-Private Window, and it also opens the Private Window, but with an empty tab. I was looking for a workaround for this but really can't find anything. I do understand that this might be an error within Firefox's end, just wanted to make sure if someone has a workaround for this. Thanks! I am quite glad that this app is also being updated, keep it up! `(*＾-＾*)`

![image](https://user-images.githubusercontent.com/69390917/172531257-7dc19853-d260-426b-be80-e959890ed143.png)

**Comment by U-C-S** [comment]
```json
    {
      "Name": "Firefox Nightly",
      "ExePath": "C:\\Program Files\\Firefox Nightly\\firefox.exe",
      "LaunchArgs": "--private-window %URL%"
    },
 ```
 
This only works with `v0.6.2` and only in browser LaunchArgs which only has `%URL%` variable support, something AlternateLaunches currently doesn't support (will add it in next version, couldn't add it in previous since I was just testing it)

**Comment by grentninja** [comment]
Alright! Thanks this worked :)
