### ISSUE TITLE
v0.6.2 crashes when hovering over scrollbar

### ISSUE THREAD

**Issue by hanjo** [U-C-S/Hurl#47]
Hi,

I noticed that a scrollbar is shown when more than five browsers are configured and the width of the window is limited accordingly.

When I tried to scroll to the right to select the 6th browser, the app crashed once I hovered the cursor over the scrollbar.

Here are the logs:
![hurl-crash1](https://user-images.githubusercontent.com/442966/172595481-6eeca7d3-ee71-4da7-a960-0f78fa3b5649.png)
![hurl-crash2](https://user-images.githubusercontent.com/442966/172595497-8b793a44-eed2-4a01-bdc9-3b9c20ed8cf6.png)

I would also like to suggest a configuration option for the number of browsers that can be seen at any one time. The scrollbar solution is logical, but quite inconvenient, since it takes a lot more time to select a browser or application that is on the 6th or later position. Maybe an option to extend the maximum width of the window would be possible? Or better yet, using a second or even third row?

**Comment by U-C-S** [comment]
I'll look into it. Though I'm guessing this is a issue with library I'm using - [WPF-UI](https://github.com/lepoco/wpfui) for scroll bars. Need to debug it.

---

> I would also like to suggest a configuration option for the number of browsers that can be seen at any one time

Yeh. Configuration for no. of browsers that can be seen is previously discussed here - https://github.com/U-C-S/Hurl/issues/25#issuecomment-1063061321 . Might Implement it soon, The App code needs a bit refactoring before that

**Comment by U-C-S** [comment]
Fixed at https://github.com/lepoco/wpfui/pull/194 and updated the package in Hurl
