### ISSUE TITLE
Clicking tray icon results cropped window

### ISSUE THREAD

**Issue by nitin2953** [U-C-S/Hurl#48]
Left clicking tray icon results cropped window
After that context menu's **Open** don't work
![Screenshot 2022-06-24 091917](https://user-images.githubusercontent.com/34852979/175475766-187e2b6b-5148-4861-8090-be0153a2a4e4.png)

**Comment by U-C-S** [comment]
Yeh.... I'm getting the same thing. I believe it's just a minor fix. Might fix it in next update (maybe v0.6.3 ??)
