### ISSUE TITLE
loads without transparency then exits

### ISSUE THREAD

**Issue by Mystqr4** [U-C-S/Hurl#50]
Hi I have been attempting to get this to work on my pc for a few versions and have hesitated to comment but it seems Hurl fails to load correctly on my PC. It will appear black rather than glass/transparent and when I hover the mouse over the scrollbar it will exit on its own. I'm not sure what is going on or why but I have attempted to install a number of versions of .NET but still no luck unless I have missed one. 

Right now Browser Select seems vastly lighter and more stable but I still have hopes for this one since it reminds me of the OG Browser Chooser with a lot more potential. 

![kAMyLb9wpv](https://user-images.githubusercontent.com/65718578/179225058-9fcc0593-148b-4d19-9c99-854b699d9603.png)

**Comment by U-C-S** [comment]
Rignt now, I already fixed scrollbars crash in unreleased version. and `.NET 6 desktop runtime` is the only thing you need to have in your system for Hurl to work.

And Both are issues related to the package hurl uses, `wpfui` which is bit unstable for lot of things in Windows 10. I had to create  patches and PR them to the package for Acrylic to work. So, I was bit experimenting on moving current codebase to either C++ or UWP or WinAppSDK style. 

Yeh, Browser Select is a lot lightweight and stable. I intend to support a lightweight version of Hurl, with bunch of stuff like acrylic, single-instances removed for that lightness. but that's a bit extra work. Im in final year of gradution......

**Comment by Mystqr4** [comment]
Great to hear from you.

Interesting. I'd imagine C++ would be the better option for compatibility and to lighten things up but I am not a programmer at all and just going off basic knowledge.
Whilst Browser Select is pretty cool and lightweight it Hurl can be great also. I have seen numerous projects attempt to replicate Browser Chooser that never quite made it this far or had this much promise. Perhaps a focus on moving the current codebase to something that does not fight you all the way would be better so you can work on it more efficiently but absolutely keep up with your studies. Nothing is more important than your life and future.
I will continue to keep an eye on this project and keep testing it with every new release.

Thanks for the reply and software development.
It's a pretty cool project.

**Comment by U-C-S** [comment]
Please do try out the new version `v0.6.3` and check if the same happens....

**Comment by Mystqr4** [comment]
Good news is that it doesn't crash anymore and the window isn't black anymore. It works fine on desktop in terms of transparency but when over the top of a folder the background goes grey. I'm not sure what the three dot menu on each icon for the browser is meant to do but just a dark grey line appears and not anything else.

Big improvement though.

**Comment by U-C-S** [comment]
Thanksi 😊

---

> three dot menu on each icon for the browser

it's #36

<img src="https://user-images.githubusercontent.com/50218121/179299067-aacd86ea-8b81-4be2-a45c-873c88561273.gif" width="500" />

I should write some code to hide it if empty or not used, like in your case. but it currently seems not possible and The project needs some refactor for that.  

Closing the issue btw. but still open to discuss.

**Comment by neoOpus** [comment]
I tried both v6.0.3 and v7 alpha and the acrylic effect isn't working, the background is black…

It would be better to have the options show on mouse over under the icon as an extended list (same dimension that just animate to show them and on mouse over of each one of them name it shows a tooltip or bubble with the arguments if this is enabled in the setting)

**Comment by U-C-S** [comment]
> I tried both v6.0.3 and v7 alpha and the acrylic effect isn't working, the background is black…

please share Screenshot and OS version

> mouse over under the icon as an extended list 

Intresting design idea. Might need to experiment if this is actually possible, without the edges of tooltip clipping off.
