### ISSUE TITLE
Everything disappeared on startup

### ISSUE THREAD

**Issue by nitin2953** [U-C-S/Hurl#53]
I have kept Hurl in startup folder,
after v0.6.3 update, all browser icons & toolbar icons disappeared, on hover they reappear

https://user-images.githubusercontent.com/34852979/179385216-8957ffc1-b0df-42fa-90d7-2156301b6267.mp4

**Comment by U-C-S** [comment]
This only happens ocassionally. I can't even debug the actual issue.

**Comment by U-C-S** [comment]
Closing this.... Since I haven't encountered it in `v0.7-alpha`. probably the new library version fixed it.

If u still find this happening in `v0.7-alpha`, comment here
