### ISSUE TITLE
[Feature Request] Grid System for more than 5 browsers.

### ISSUE THREAD

**Issue by rp1231** [U-C-S/Hurl#54]
More than 5 browsers produces a scroll bar which is not really ideal.
Maybe a grid system can be implemented with multiple rows?
Thanks

**Comment by U-C-S** [comment]
This is something I want take a look soon. Im thinking something similar to win11 start

![image](https://user-images.githubusercontent.com/50218121/184564459-99d98bf5-17f6-483c-945f-21800b1d2414.png)

**Comment by nitin2953** [comment]
Hey @U-C-S I know that I don't like the design initially but after seeing a screenshot of [browserosaurus v10](https://github.com/will-stone/browserosaurus/issues/200#issuecomment-637811592), I think it will look great in Hurl

![browserosaurus-macos-1 1](https://user-images.githubusercontent.com/34852979/185406320-0dbba856-9360-4751-ada4-9ac7e77d636d.jpg)

[single row ↗](https://user-images.githubusercontent.com/654103/83569589-a1c60d00-a51c-11ea-8636-a57192652d64.png)

[triple row ↗](https://applech2.com/wp-content/uploads/2020/06/Browserosaurus-for-Mac-v10-Hero.jpg)

**Comment by U-C-S** [comment]
Yeh. I was thinking where to put the keyboard shortcut keys, It handled that well. Ill try to post some of the screenshots of some designs I experimented over here in coming week (currently upgrading my laptop to a newer one, waiting hence going slow)

**Comment by U-C-S** [comment]
Oops, i didn't notice and forgot to address the issue

I currently went with
A grid and now with a resizable window for more control in v0.7

Keyboard shortcuts cues are still a question.
