### ISSUE TITLE
Non-functioning On Windows 10 [Version 10.0.19044.2130]

### ISSUE THREAD

**Issue by TooSpooky** [U-C-S/Hurl#60]
Hello,

Just a heads up that the latest update seems to not function at all on windows 10, it just refuses to launch entirely. I've been using the 7.0.0 Alpha prior to this just fine aside from some weird lag when moving the window which is no biggie but with the update it now doesn't even launch.

I've also made sure to update .Net 6 runtime. 

Thanks for your time and take care!

**Comment by U-C-S** [comment]
Thanks for reporting.... Ill look into it and deploy a quick fix.

**Comment by U-C-S** [comment]
Released `v0.7.1`. It fixes the crash you reported.

https://github.com/U-C-S/Hurl/releases/tag/v0.7.1

**Comment by yat2k** [comment]
Just a image for v0.7 crash message in win10
![image](https://user-images.githubusercontent.com/63180414/199179250-2d1042d5-d810-43f9-ae33-53af51631c33.png)

**Comment by TooSpooky** [comment]
Haha that was fast, sweet and it's working perfectly. No more lag when dragging as well and the solid background with border is nice. Thanks!
