### ISSUE TITLE
Acrylic Weirdness

### ISSUE THREAD

**Issue by riotrah** [U-C-S/Hurl#71]
Hello again,

First here's what I'm seeing, ![image](https://user-images.githubusercontent.com/22646419/233538065-b49fe068-7d1a-468c-8478-0cadbaa67307.png).

I read #57 but I cannot tell if your screenshot is showing the same thing or not. I would prefer Acrylic over Mica, but it's not the biggest issue so don't consider this blocking - either look better than this haha.

> Windows 11 22621.1555
<details><summary>My config:</summary>

```json
{
  "LastUpdated": "4/6/2023 8:59:49 PM",
  "Browsers": [
    {
      "Name": "Vivaldi",
      "ExePath": "C:\\Program Files\\Vivaldi\\Application\\vivaldi.exe"
    },
    {
      "Name": "Opera GX Stable",
      "ExePath": "\u0022C:\\Program Files\\Opera GX\\Launcher.exe\u0022"
    },
    {
      "Name": "Brave",
      "ExePath": "C:\\Program Files\\BraveSoftware\\Brave-Browser\\Application\\brave.exe",
      "Hidden": true
    },
    {
      "Name": "Firefox",
      "ExePath": "C:\\Program Files\\Mozilla Firefox\\firefox.exe",
      "Hidden": true
    },
    {
      "Name": "Google Chrome",
      "ExePath": "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"
    },
    {
      "Name": "Microsoft Edge",
      "ExePath": "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"
    }
  ],
  "AppSettings": {
    "LaunchUnderMouse": true,
    "NoWhiteBorder": true,
    "BackgroundType": "acrylic",
    "WindowSize": [
      560,
      220
    ]
  },
  "AutoRoutingRules": []
}
```
</details>

**Comment by U-C-S** [comment]
yeh... Acrylic is weird, because it was never supposed to work with WPF framework that I'm using to build Hurl, but through some bindings and magic idk, It was made to work. 

I assume this must be due to enabling `Show accent color on title bars and window borders` option in Windows Settings > Personalization > Accent Color.

**Comment by riotrah** [comment]
Interesting. 

And that's what I would have assumed as well, however, it's not!

**Comment by U-C-S** [comment]
Ah... I'm not sure what's causing that then. I enabled the `accent color on title bars....` I could see the colored title bar. (I use 22624.1616)
I will see what I can do from the code. I have got couple of workaround ideas now....

**Comment by lucaspestana** [comment]
Howdy! I have a few questions here!

I noticed that, in his configuration file (which I've just copied and adapted, so thanks!), @riotrah used the setting *`No`*`WhiteBorder` (set to `true`)-- however, the documentation mentions only it as ***`Use`***`WhiteBorder` (I set mine to `false` and now it's working). Which one is the correct name? Are _both_ usable (and therefore redundant)?

Also: my apologies if this is not the right place to ask this, but… I'm a Windows 10 22H2 user, and setting BackgroundType to the `acrylic` ~or `mica` (obviously, duh)~ doesn't work.
So, Windows 10 users can only use the solid color background and acrylic isn't supported at all?

Thank you, I look forward to seeing the launch of version 0.8, hooray! (And I can't compliment this app enough, I absolutely love it!!)

**Comment by U-C-S** [comment]
`NoWhiteBorder` is v0.8 alpha version's setting (renamed from UseWhiteBorder)

Yeh, win10 doesn't support acrylic for now. I tried making it work, but it just causes lot of problems. In both win10 and 11, but win11 acrylic is bit stable and simpler to implement.

Thank you for the compliments 🥰

**Comment by U-C-S** [comment]
Closing this
