### ISSUE TITLE
Automatically install required .NET Desktop Runtime 7.0.9

### ISSUE THREAD

**Issue by AaronFeledy** [U-C-S/Hurl#75]
After updating to v0.8 On Windows 11, I was prompted to update my .NET Desktop Runtime to 7.0.9 or later. The prompt included a button to update, but that didn't seem to do anything but close the window. Running `winget install Microsoft.DotNet.DesktopRuntime.7` made easy work of silently downloading and installing the runtime. Perhaps the installer could do this automatically.

**Comment by AaronFeledy** [comment]
Looks like you can also build the dependencies into the exe so the runtime is not needed: https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview

**Comment by U-C-S** [comment]
Single files are freaking huge.... (atleast 120MB on disk), .NET Desktop Runtime has better advantages especially since powertoys and others depend and install it

I will look into a small `v0.8.1` release to include this. I already found a way to do this. Just that I couldn't spare enough time on working on it.

**Comment by U-C-S** [comment]
@rp1231 Weird that getting the same in 2 of 4 systems I have tested now, not sure whats the pattern. I will try rebuild and update the release once again. Thanks for notifying.

**Comment by U-C-S** [comment]
@rp1231 It's fixed now... Redownload the file and try it again

**Comment by CamiloGTR** [comment]
> @rp1231 It's fixed now... Redownload the file and try it again

Hi!. I'm updating from previous version and getting this error:

![image](https://github.com/U-C-S/Hurl/assets/16406219/6a43347a-0588-414e-aabd-022cc87720db)

However:
![image](https://github.com/U-C-S/Hurl/assets/16406219/7b051f95-654c-4d55-979c-9e4dc7da935a)

Any help is appreciated! Thanks

**Comment by U-C-S** [comment]
https://github.com/BartoszCichecki/LenovoLegionToolkit/blob/master/InnoDependencies/install_dotnet.iss
