### ISSUE TITLE
Building from Source improvements

### ISSUE THREAD

**Issue by natevoci** [U-C-S/Hurl#76]
I found that the Building from Source instructions in README.md were missing a couple of things.

First, After checking out the repo I needed to do a git submodule init to load the Wpfui project.

Second, I was getting a build error because the CommunityToolkit.Labs.WinUI.SettingsControls package could not be found. Eventually I figured out I could fix this by adding this package source in the settings of the NuGet Package Manager
https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-Labs/nuget/v3/index.json

**Comment by U-C-S** [comment]
Temporarily removed use of wpfui git submodule (since a new stable version is released) and Hurl Settings Project from sln project file.

Will add to README when I have a working version
