### ISSUE TITLE
Auto Routing Rules don't apply Launch Args

### ISSUE THREAD

**Issue by nathanbabcock** [U-C-S/Hurl#80]
First off, thank you for the great program, it is designed **so** much nicer than other apps like it. 👏

Here's my understanding of the issue — in [AutoRulesCheck.cs](https://github.com/U-C-S/Hurl/blob/9b381c2d05058f8c683b80588bf35cd9384acdcc/Source/Hurl.BrowserSelector/Helpers/AutoRulesCheck.cs#L73C60-L73C60), the browser is started with this command:

```cs
Process.Start(x.ExePath, link);
```

It's missing the `LaunchArgs` part that is included elsewhere, such as [BrowsersList.xaml.cs](https://github.com/U-C-S/Hurl/blob/9b381c2d05058f8c683b80588bf35cd9384acdcc/Source/Hurl.BrowserSelector/Controls/BrowsersList.xaml.cs#L87), there's some extra logic to include the `LaunchArgs` and apply them to the command:

```cs
Process.Start(browser.ExePath, Link + " " + browser.LaunchArgs);
```

For reference, my use case is this: I have a different Github account for my work, and a separate Chrome profile where I'm logged into my work Github. But when I click PR links in Slack, it randomly opens in either my default profile or the work profile (whichever one I most recently opened a tab in).

**Comment by U-C-S** [comment]
Yes, I will release a new version soon to add this. Thanks for me making aware of this.
