### ISSUE TITLE
Possible issue with firefox profiles

### ISSUE THREAD

**Issue by rainingkittens** [U-C-S/Hurl#83]
This could just as easily be my personal failings with code, but I can't get hurl to work with opening any of the firefox profiles I have whether as alternate launches or just as separate browsers. 🆘 

Here is the code as separate browser:
```
{
  "LastUpdated": "20/12/2023 12:45:39 PM",
  "Browsers": [
    {
      "Name": "Firefox",
      "ExePath": "C:\\Program Files\\Mozilla Firefox\\firefox.exe"
     },
{
"Name": "Firefox - downloading",
"ExePath": "\"C:\Program Files\Mozilla Firefox\firefox.exe\" -P downloading"
},

    {
      "Name": "Microsoft Edge",
      "ExePath": "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"
    }
  ]
}
```

and here is it as an alternate launch:
```
{
  "LastUpdated": "20/12/2023 12:45:39 PM",
  "Browsers": [
    {
      "Name": "Firefox",
      "ExePath": "C:\\Program Files\\Mozilla Firefox\\firefox.exe"
      "AlternateLaunches": [
        {
          "ItemName": "downloading",
          "LaunchArgs": "-P downloading"
        }
		]
     },

    {
      "Name": "Microsoft Edge",
      "ExePath": "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"
    }
  ]
}
```

Please help!

**Comment by U-C-S** [comment]
Sorry for late response. Bit busy this month.

```json
{
  "Name": "Firefox Nightly",
  "ExePath": "C:\\Program Files\\Firefox Nightly\\firefox.exe",
  "LaunchArgs": "-P downloading"
},
```

That works for me. You need to use separate property `LaunchArgs` for args when adding it directly.

**Comment by rainingkittens** [comment]
It's still not working for me :(
I did the code like so:

```
{
  "LastUpdated": "16/06/2023 5:19:10 PM",
  "Browsers": [
    {
      "Name": "Edge",
      "ExePath": "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"
    },
    {
     "Name": "Firefox - downloading",
     "ExePath": "C:\\Program Files\\Mozilla Firefox\\firefox.exe"
     "LaunchArgs": "-P downloading"
    }
	  
	  
  ]
 
  
}
```

and it still didn't work for me. the target for the firefox profile shortcut shows as: `"C:\Program Files\Mozilla Firefox\firefox.exe" -P downloading`

so it should work right? I don't know what's going on or what could possibly be wrong if it's working for you.

**Comment by U-C-S** [comment]
Sorry, I didn't notice ur reply here

Looks like you are missing a comma `,` after `"ExePath": "C:\\Program Files\\Mozilla Firefox\\firefox.exe"`

**Comment by rainingkittens** [comment]
Thank you! It's now working! I have come across a new issue when adding rules through the new popup menu thingy, should I open another issue or just add it here?

**Comment by U-C-S** [comment]
>  a new issue when adding rules through the new popup menu thingy

Mention it here for now, That adding rules popup is getting redone into new window called "Ruleset Manager".  I will fix it that has the same issue

**Comment by rainingkittens** [comment]
sure thing 😊 so basically what happens is that I use the popup to add a new rule such as:
`r$.*stack\\.com\\.au.*`
and it won't work at first so I check the UserSettings json and it adds additional backwards slashes every time so it will look like this:
`r$.*stack\\\.com\\\.au.*`
thus causing the rule to no longer work. but I can manually edit out the extra slashes and it will then start working. ideally if you could figure out a way to stop the extra backwards slashes from being added in the first place though it would be a lot simpler to add rules! 

thanks!
