### ISSUE TITLE
Don't run in background/system tray

### ISSUE THREAD

**Issue by nathanbabcock** [U-C-S/Hurl#84]
I would prefer if the program did not stay idle in the background and system tray at all times. I understand that the startup time for the program/UI can be long (I mean several seconds), and that the solution to this problem was to keep it loaded in advance. But I think it would be much better to just have an `.exe` with a more-or-less instant startup time (particularly for auto-routing rules).

If this isn't a design direction you're interested in going in, feel free to close this issue, no worries — it's just my personal preference and user feedback.

**Comment by U-C-S** [comment]
I really want to do something like this. C#/.NET with WPF currently doesnt do AoT Compilation which is really useful for instant startup times. If I have time, I want to port Hurl to C++ .
