### ISSUE TITLE
After upgrading from 0.8.0 to 0.8.1, Hurl is no longer my default browser

### ISSUE THREAD

**Issue by stamminator** [U-C-S/Hurl#88]
I did an in-place upgrade (installed 0.8.1 without first manually uninstalling 0.8.0), and afterwards, Hurl was no longer working. Looks like it's no longer my default browser.

After resetting Hurl to my default browser (which unfortunately is somewhat clunky in Windows 11), it works fine.

**Comment by U-C-S** [comment]
> in-place upgrade (installed 0.8.1 without first manually uninstalling 0.8.0)

This should work fine.

I will take a look again, I didn't experience this while I am dogfooding it

**Comment by U-C-S** [comment]
I tried the same. Can't reproduce it now. probably Windows being weird with default browsers. 

If you face it again, Feel free to open this again.
