### ISSUE TITLE
Rules: anything but automatic, don't know the syntax

### ISSUE THREAD

**Issue by Jay-o-Way** [U-C-S/Hurl#91]
When I click a link and Hurl responds, I want to add a rule for the given website/domain.

- The UI that pops-up, does not use the URL at all.
- The placeholder shows `s$google.com | g$*.google.com` and more, but I have no idea what `s$` or `g$` mean, or what any other possible/allowed variables are. At bare minimum, you must link to https://github.com/U-C-S/Hurl/wiki/Auto-Open-Rules, but ideally this info is available in the UI. Note that wiki says "simple text" uses **no** prefix, but the JSON expects `s$`.
- The documentation does not mention the `id`.
- Is there an _easy_ way to declare both `domain.com` and `*.domain.com` in one rule?

**Comment by Jay-o-Way** [comment]
Suggestion for a different approach: add rules to the browser info.
Example JSON:
```json
  "Browsers": [
    {
      "Name": "Firefox",
      "ExePath": "C:\\Program Files\\Mozilla Firefox\\firefox.exe"
    },
    {
      "Name": "Google Chrome",
      "ExePath": "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"
      "Rules": ["g$*.google.com", "github.com"]
    },
    {
      "Name": "Microsoft Edge",
      "ExePath": "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"
      "Rules": ["g$*.microsoft.com"]
    }

```

**Comment by U-C-S** [comment]
> Suggestion for a different approach: add rules to the browser info.

Rules are made with having its own UI to manage them. But the work on it is halted due to issues with WinAppSdk. I am looking to port that UI to wpf soon.

I want them to be reordered, have prioritized one which the way you suggested doesn't solve

**Comment by U-C-S** [comment]
>  At bare minimum, you must link to https://github.com/U-C-S/Hurl/wiki/Auto-Open-Rules, but ideally this info is available in the UI. Note that wiki says "simple text" uses no prefix, but the JSON expects s$

I will include the link to wiki for now and fix it in the wiki, Thanks

**Comment by Jay-o-Way** [comment]
Aside from that, it doesn't seem to work for me... Am I doing something wrong?
![image](https://github.com/U-C-S/Hurl/assets/65828559/a49d910a-1b6f-4574-890e-7a786f63f859)

**Comment by Jay-o-Way** [comment]
Looks like a bug on my end. Even when I copy `https://github.com/` from the .lnk file and use that in a rule (with or without `s$` prefix) it still keeps asking...

**Comment by U-C-S** [comment]
Closing this... Updated the docs and #105
