### ISSUE TITLE
cant get this regular work.

### ISSUE THREAD

**Issue by mannfuri** [U-C-S/Hurl#93]
```
  "Rulesets": [
    {
      "Id": 1304,
      "Rules": [
        "g$*.atlassian.net*"
      ],
      "BrowserName": "Firefox Developer Edition"
    }
  ]
```

i wanna open all url from atlassian.net with my Firefox Developer Edition

**Comment by U-C-S** [comment]
Can you post your entire UserSettings.json here ??
probably an issue with same BrowserName not existing under `Browsers` property

**Comment by mannfuri** [comment]
> Can you post your entire UserSettings.json here ?? probably an issue with same BrowserName not existing under `Browsers` property
> 
> also, Your rule only opens URLs like https://abcd.atlassian.net/blah and does not work with https://atlassian.net/blah

thanks for your reply！
ill post my json file when i arrive home.
thanks again！

**Comment by mannfuri** [comment]
```
{
  "$schema": "https://raw.githubusercontent.com/U-C-S/Hurl/main/Utils/UserSettings.schema.json",
  "LastUpdated": "2024/3/4 20:27:16",
  "Browsers": [
    {
      "Name": "Firefox",
      "ExePath": "C:\\Program Files\\Mozilla Firefox\\firefox.exe"
    },
    {
      "Name": "Google Chrome",
      "ExePath": "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"
    },
    {
      "Name": "Firefox Developer Edition",
      "ExePath": "C:\\Program Files\\Firefox Developer Edition\\firefox.exe"
    },
    {
      "Name": "Microsoft Edge",
      "ExePath": "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"
    }
  ],
  "AppSettings": {
    "LaunchUnderMouse": false,
    "NoWhiteBorder": false,
    "BackgroundType": "mica",
    "WindowSize": [
      560,
      220
    ]
  },
  "Rulesets": [
    {
      "Id": 1304,
      "Rules": [
        "g$*atlassian.net*",
        "g$*google.com*"
      ],
      "BrowserName": "Firefox Developer Edition"
    },
    {
      "Id": 7940,
      "Rules": [
        "g$*gooogle.com"
      ],
      "BrowserName": "Firefox Developer Edition"
    }
  ]
}
```

this is how my C:\Users\username\AppData\Roaming\Hurl\UserSettings.json looks like.

with this setting file.

With this setting file, I am unable to open URLs containing GOOGLE.COM, please refer to the screen recording video.

https://github.com/U-C-S/Hurl/assets/91338215/645e2fce-20f2-4e70-a64d-fdc8f89ef8a8

**Comment by U-C-S** [comment]
![image](https://github.com/U-C-S/Hurl/assets/50218121/807c5337-e6df-4d05-897e-af1df854c2d1)

**Comment by U-C-S** [comment]
I realize Glob have a severe limitation with `/`s (i.e it doesn't include `/` as part of `*`)
Might have to create own glob like syntax without the limitations
