### ISSUE TITLE
Reporting a BUG

### ISSUE THREAD

**Issue by mannfuri** [U-C-S/Hurl#97]
When my UserSetting.json file is not in a valid JSON format, running hurl.exe does produce an error, but the hurl.exe program does not terminate.
I have to manually kill the hurl.exe process and fix the json file before I can start hurl.exe again.
Is it possible to automatically stop the hurl.exe process when an invalid json is detected?

**Comment by U-C-S** [comment]
I think this is fixed in the newer v0.8.1, can verify if you are running the newer version ?

**Comment by mannfuri** [comment]
yes im running the v0.8.1

**Comment by U-C-S** [comment]
Weird.... I will take a look again today, Thanks for reporting.
